lsn-5/3-webpackDevServer: fix => update webpack-cli from 4.9.2 to 4.10.0, because had an error "1% setup initialize[webpack-cli] TypeError: cli.isMultipleCompiler is not a function"